name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t 90amandas388/wisecow:latest .
        docker push 90amandas388/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Create .kube directory
      run: |
        mkdir -p $HOME/.kube

    - name: Replace Hostname in Kubeconfig
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
        sed -i 's/kubernetes.docker.internal/172.17.0.1/g' $HOME/.kube/config

    - name: Deploy to Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        kubectl config get-contexts
        kubectl config current-context
        kubectl apply -f deployment.yaml --validate=false
        kubectl apply -f service.yaml --validate=false
        kubectl apply -f issuer.yaml --validate=false
        kubectl apply -f ingress.yaml --validate=false
